# Generated by Django 5.2.3 on 2025-06-21 23:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('domain', models.CharField(max_length=255)),
                ('page_title', models.CharField(blank=True, max_length=500, null=True)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('processing', 'Se procesează'), ('completed', 'Completat'), ('failed', 'Eșuat')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_tags', models.JSONField(blank=True, default=dict)),
                ('company_info', models.JSONField(blank=True, default=dict)),
                ('headings', models.JSONField(blank=True, default=dict)),
                ('paragraphs', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('buttons', models.JSONField(blank=True, default=list)),
                ('forms', models.JSONField(blank=True, default=list)),
                ('lists', models.JSONField(blank=True, default=list)),
                ('tables', models.JSONField(blank=True, default=list)),
                ('scripts', models.JSONField(blank=True, default=list)),
                ('styles', models.JSONField(blank=True, default=list)),
                ('contact_info', models.JSONField(blank=True, default=dict)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('statistics', models.JSONField(blank=True, default=list)),
                ('css_classes', models.JSONField(blank=True, default=list)),
                ('element_ids', models.JSONField(blank=True, default=list)),
                ('important_divs', models.JSONField(blank=True, default=list)),
                ('important_spans', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraped_site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='auth_app.scrapedsite')),
            ],
        ),
        migrations.CreateModel(
            name='AIPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('income', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=100)),
                ('interests', models.JSONField(default=list)),
                ('problems', models.JSONField(default=list)),
                ('motivations', models.JSONField(default=list)),
                ('online_behavior', models.TextField()),
                ('buying_preferences', models.TextField()),
                ('communication_channels', models.JSONField(default=list)),
                ('objections', models.JSONField(default=list)),
                ('business_type', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('target_market', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scraped_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='auth_app.scrapedsite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
