# Generated by Django 5.2.3 on 2025-06-22 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('strategy_type', models.CharField(choices=[('marketing', 'Strategie de Marketing'), ('content', 'Strategie de Conținut'), ('social_media', 'Strategie Social Media'), ('seo', 'Strategie SEO'), ('conversion', 'Strategie de Conversie'), ('branding', 'Strategie de Branding'), ('customer_retention', 'Strategie de Retenție Clienți'), ('growth', 'Strategie de Creștere')], max_length=100)),
                ('site_analysis', models.JSONField(blank=True, default=dict)),
                ('persona_insights', models.JSONField(blank=True, default=dict)),
                ('target_audience', models.JSONField(blank=True, default=dict)),
                ('key_messages', models.JSONField(blank=True, default=list)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('tactics', models.JSONField(blank=True, default=list)),
                ('timeline', models.JSONField(blank=True, default=dict)),
                ('budget_estimate', models.JSONField(blank=True, default=dict)),
                ('kpis', models.JSONField(blank=True, default=list)),
                ('implementation_steps', models.JSONField(blank=True, default=list)),
                ('resources_needed', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Ciornă'), ('active', 'Activă'), ('implemented', 'Implementată'), ('paused', 'Pusă pe pauză'), ('completed', 'Finalizată')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Scăzută'), ('medium', 'Medie'), ('high', 'Ridicată'), ('critical', 'Critică')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('personas', models.ManyToManyField(blank=True, related_name='strategies', to='auth_app.aipersona')),
                ('scraped_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='auth_app.scrapedsite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Strategies',
                'ordering': ['-created_at'],
            },
        ),
    ]
