# Generated by Django 5.2.3 on 2025-06-21 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('income', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=100)),
                ('interests', models.JSONField(default=list)),
                ('problems', models.JSONField(default=list)),
                ('motivations', models.JSONField(default=list)),
                ('online_behavior', models.TextField()),
                ('buying_preferences', models.TextField()),
                ('communication_channels', models.JSONField(default=list)),
                ('objections', models.JSONField(default=list)),
                ('business_type', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('target_market', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
