# Generated by Django 5.2.3 on 2025-06-22 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_strategy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Conținutul postării')),
                ('image_prompt', models.TextField(help_text='Prompt pentru generarea imaginii')),
                ('post_type', models.CharField(choices=[('social_media', 'Social Media'), ('blog', 'Blog Post'), ('email', 'Email Marketing'), ('advertisement', 'Advertisement'), ('content_marketing', 'Content Marketing')], default='social_media', max_length=50)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('blog', 'Blog'), ('email', 'Email'), ('general', 'General')], default='general', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Ciornă'), ('ready', 'Gata de publicare'), ('scheduled', 'Programată'), ('published', 'Publicată'), ('archived', 'Arhivată')], default='draft', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('engagement_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personas', models.ManyToManyField(blank=True, related_name='posts', to='auth_app.aipersona')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='auth_app.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
