# Generated by Django 5.2.3 on 2025-06-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='generated_image',
            field=models.ImageField(blank=True, help_text='Imaginea generată pentru postare', null=True, upload_to='generated_images/'),
        ),
    ]
