# Generated by Django 5.2.3 on 2025-06-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_post_generated_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='facebook_post_id',
            field=models.CharField(blank=True, help_text='ID-ul postării pe Facebook', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='facebook_posted',
            field=models.BooleanField(default=False, help_text='Indică dacă postarea a fost trimisă pe Facebook'),
        ),
    ]
